services:
  database:
    image: postgres:17-alpine
    container_name: product_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product_db
    ports:
      - '5432:5432'
    volumes:
      - product_db:/var/lib/postgresql/data

  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-api
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/product_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - '8081:8081'
      - '8000:8000'
    depends_on:
      - database

volumes:
  product_db: