name: CI Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "feature/**"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:17-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: product_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build the application
        run: make build

      - name: Run tests
        env:
          SPRING_PROFILES_ACTIVE: test
        run: make test

      - name: Containerize and deploy (WIP)
        run: make containerize
        #TODO deploy

      #TODO add sonar, jacoco, deployment...
